spring:
  application:
    name: discovery

server:
  port: 8100

eureka:
  instance:
    hostname: localhost
    # 服务失效时间，Eureka多长时间没收到服务的renew操作，就剔除该服务，默认90秒
    #leaseExpirationDurationInSeconds: 15
  #server:
    # eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    #evictionIntervalTimerInMs: 20000
    # 自我保护模式（默认为true）
    #enable-self-preservation: true
    # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    #eviction-interval-timer-in-ms: 5000
  client:
    # 是否注册到其它服务（默认为true）
    registerWithEureka: false
    # 是否需要拉取服务信息（默认为true）
    fetchRegistry: false
    # 服务地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/